### ISSUE TITLE
Any effort for .net core version? 

### ISSUE THREAD

**Issue by KamranShahid** [Mobile-Connect/.net_server_side_library#5]
Is there any plan for  .net core version? 
Library in .net standard >= 2.0 which i can consume in my .net core 3.0 api's

**Comment by KamranShahid** [comment]
Anybody looking into this implementation any more?

**Comment by KamranShahid** [comment]
Any Update?

**Comment by AlexA1QA** [comment]
Hello @KamranShahid , the solution is no longer supported. Please, update your .net standard to 3.0 version.
